name: “python-tests”
on: [pull_request]

jobs:
  tests:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.10"

        - name: Get poetry
          uses: abatilo/actions-poetry@v3

        - name: Run tests
          run: poetry run tests